### ISSUE TITLE
Remove .travis.yml file

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/rhof-cli#23]

**Comment by abinjohn123** [comment]
Hey @arshadkazmi42, may I take this up? I'm new to the contribution scene.

**Comment by arshadkazmi42** [comment]
@abinjohn123 Sure go ahead.

**Comment by abinjohn123** [comment]
@arshadkazmi42, I saw these errors popping up when executing `yarn test`. They're coming up in the master branch as well. Does anything have to be done about this or can I go ahead?

![image](https://user-images.githubusercontent.com/15942221/185294934-f06cca32-00d8-44d4-a119-33fb3d6e9a5c.png)

**Comment by arshadkazmi42** [comment]
Can you check in your code and create a pull request, so I will be able to check the changes.

**Comment by arshadkazmi42** [comment]
Also, try using npm 
I think we use NPM for this project not yarn

**Comment by abinjohn123** [comment]
The problem seems to be with my windows / editor. Even after setting the default `End of Line Sequence` as LF, the editor opens the .JS files in CRLF format.

I can think of three workarounds:
1. update `"linebreak-style": ["error", "unix"]` in the .eslintrc.json file to `"linebreak-style": ["error", "windows"],`
2. change End of Line Sequence of all files from CRLF to LF. This, however, would mark all the JS files as `modified` by git
3. Since the issue is only to remove the `.travis.yml` file, which doesn't necessarily modify any of the other files, I can just proceed with committing that change and skip the tests.

Please do let me know if you have encountered something similar before or if any of the workarounds are good to go.

**Comment by arshadkazmi42** [comment]
@abinjohn123 Can you try changing in `.eslintrc.json` line 16 to this `"linebreak-style": 0` 

Let me know if this helps

**Comment by arshadkazmi42** [comment]
You can check in the code, with the error. So we can review the changes together, seems there is some issue with linebreak eslint rule.
It either supports windows or unix.

I will have to look into this more for a proper fix. for now let's check in the change as is

**Comment by abinjohn123** [comment]
> The problem seems to be with my windows / editor. Even after setting the default `End of Line Sequence` as LF, the editor opens the .JS files in CRLF format.
> 
> I can think of three workarounds:
> 
> 1. update `"linebreak-style": ["error", "unix"]` in the .eslintrc.json file to `"linebreak-style": ["error", "windows"],`
> 2. change End of Line Sequence of all files from CRLF to LF. This, however, would mark all the JS files as `modified` by git
> 3. Since the issue is only to remove the `.travis.yml` file, which doesn't necessarily modify any of the other files, I can just proceed with committing that change and skip the tests.
> 
> Please do let me know if you have encountered something similar before or if any of the workarounds are good to go.

This is solved! It was git that was causing the problem while cloning the repo.
